huntflow/huntflow-webhook-models-py

huntflow_webhook_models/common_models/vacancy.py, pyproject.toml
https://huntflow.atlassian.net/browse/INT-179
=> Fix account division

huntflow_webhook_models/common_models/vacancy.py, pyproject.toml
https://huntflow.atlassian.net/browse/INT-180
Changed event.applicant_log.vacancy.created datetime -> date
=> INT-180 Fix vacancy created field

huntflow_webhook_models/base.py, huntflow_webhook_models/common_models/vacancy.py, huntflow_webhook_models/consts.py, huntflow_webhook_models/vacancy.py, pyproject.toml
https://huntflow.atlassian.net/browse/INT-195
Added vacancy webhook request model
=> [INT-195] Add vacancy webhook request model

huntflow_webhook_models/__init__.py, huntflow_webhook_models/common_models/vacancy_request.py, huntflow_webhook_models/consts.py, huntflow_webhook_models/vacancy_request.py
https://huntflow.atlassian.net/browse/INT-196
=> Int 196 add vacancy request hook model

huntflow_webhook_models/common_models/applicant.py
https://huntflow.atlassian.net/browse/INT-203
=> Fix field type

huntflow_webhook_models/common_models/hf_base.py, huntflow_webhook_models/common_models/response.py, huntflow_webhook_models/common_models/vacancy.py, huntflow_webhook_models/consts.py, huntflow_webhook_models/response.py
https://huntflow.atlassian.net/browse/INT-222
=> [INT-222] - Create ResponseHookRequest.

huntflow_webhook_models/base.py, huntflow_webhook_models/common_models/applicant.py, huntflow_webhook_models/common_models/calendar_event.py, huntflow_webhook_models/common_models/hf_base.py, huntflow_webhook_models/common_models/response.py, huntflow_webhook_models/common_models/survey_questionary.py, huntflow_webhook_models/common_models/vacancy.py, huntflow_webhook_models/common_models/vacancy_request.py, huntflow_webhook_models/consts.py, pdm.lock, pyproject.toml
https://huntflow.atlassian.net/browse/INT-307
=> [INT-307]- Switch to pydantic 2.

huntflow_webhook_models/common_models/applicant.py, huntflow_webhook_models/common_models/recruitment_evaluation.py, huntflow_webhook_models/common_models/response.py, huntflow_webhook_models/common_models/survey_answer.py, huntflow_webhook_models/common_models/survey_questionary.py
https://huntflow.atlassian.net/browse/INT-332
=> [INT-332] Fix descriptions and examples

huntflow_webhook_models/common_models/applicant.py, pyproject.toml
https://huntflow.atlassian.net/browse/INT-411
=> [INT-411] - Make first_name and last_name optional in the Applicant model.

pyproject.toml
https://huntflow.atlassian.net/browse/INT-625
=> [INT-625] - Up version -> 0.1.5

huntflow_webhook_models/common_models/vacancy.py, pyproject.toml
https://huntflow.atlassian.net/browse/INT-635
=> [INT-635] - fix Vacancy model

huntflow_webhook_models/__init__.py, pyproject.toml
https://huntflow.atlassian.net/browse/INT-638
=> [INT-638] - Delete extra="forbid".

huntflow_webhook_models/base.py, huntflow_webhook_models/common_models/applicant.py, huntflow_webhook_models/common_models/hf_base.py, huntflow_webhook_models/common_models/recruitment_evaluation.py, huntflow_webhook_models/common_models/survey_answer.py, huntflow_webhook_models/common_models/vacancy.py, pyproject.toml
https://huntflow.atlassian.net/browse/INT-663
=> [INT-663] - Fix models.

huntflow_webhook_models/common_models/applicant.py, huntflow_webhook_models/common_models/vacancy_request.py, huntflow_webhook_models/vacancy.py, pyproject.toml
https://huntflow.atlassian.net/browse/INT-667
=> [INT-667] - Fix models.

.github/workflows/python-linters.yml, huntflow_webhook_models/common_models/calendar_event.py, huntflow_webhook_models/common_models/hf_base.py, huntflow_webhook_models/consts.py, pdm.lock, pyproject.toml
https://huntflow.atlassian.net/browse/INT-683
=> [INT-683] - Fix models.

huntflow_webhook_models/common_models/hf_base.py, huntflow_webhook_models/common_models/vacancy.py, pyproject.toml
https://huntflow.atlassian.net/browse/INT-705
=> [INT-705] - Fix AccountDivision model.

.github/workflows/publish.yml, .github/workflows/python-linters.yml
https://huntflow.atlassian.net/browse/INT-789
=> [INT-789] - Fix pdm install step.

huntflow_webhook_models/common_models/applicant.py, huntflow_webhook_models/common_models/vacancy.py, pyproject.toml
https://huntflow.atlassian.net/browse/INT-791
=> [INT-791] - Fix models.

huntflow_webhook_models/common_models/vacancy.py, pyproject.toml
https://huntflow.atlassian.net/browse/INT-809
=> [INT-809] - Add vacancy_frame_fill_quota to the Vacancy model.

.github/workflows/publish.yml
https://huntflow.atlassian.net/browse/INT-994
=> [INT-994] - Fix publish github action.

huntflow_webhook_models/common_models/calendar_event.py, pyproject.toml
https://huntflow.atlassian.net/browse/INT-1010
=> [INT-1010] - Fix CalendarEventReminder model.

huntflow_webhook_models/common_models/vacancy.py, huntflow_webhook_models/common_models/vacancy_request.py, pyproject.toml
https://huntflow.atlassian.net/browse/INT-1206
=> [INT-1206] - Fix imports.
